### ISSUE TITLE
pop_trimOutlier calculates channel STD differently from trimOutlier?

### ISSUE THREAD

**Issue by mireiatorralba** [sccn/trimOutlier#1]
Hi,
I came across a weird result using pop_trimOutlier. Selecting the threshold based on the graphs, results on 0 channels discarded according to the STD calculated on 100 bins, but later, when pop_trimOutlier calls trimOutlier, as the STD is recalculated in a different way (as far as I understand, is directly the STD of all the channel activity) this results in all my channels being rejected. Here is the message I obtain in Matlab:

allEEG3 =pop_trimOutlier(allEEG);

0 channels will be rejected for upper bound threshold.
0 channels will be rejected for lower bound threshold.
Removing 30 channel(s)...
Event resorted by increasing latencies.

The following channels were removed:
  Columns 1 through 13

    {'Fp1'}    {'Fz'}    {'F3'}    {'F7'}    {'FC5'}    {'FC1'}    {'C3'}    {'T7'}    {'Fpz'}    {'CP5'}    {'CP1'}    {'Pz'}    {'P3'}

  Columns 14 through 26

    {'P7'}    {'O1'}    {'Oz'}    {'O2'}    {'P4'}    {'P8'}    {'CP6'}    {'CP2'}    {'Cz'}    {'C4'}    {'T8'}    {'FC6'}    {'FC2'}

  Columns 27 through 30

    {'F4'}    {'F8'}    {'Fp2'}    {'FCz'}

Could you explain why the SD in pop_trimOutlier is calculated differently than in trimOutlier? Thanks!

**Comment by arnodelorme** [comment]
@MakotoMiyakoshi

**Comment by mireiatorralba** [comment]
Hi!
The issue is easy to solve, just by commenting line 48 in trimOutlier.m:
stdAllPnts  = std(EEG.data(:,:),0,2);

And replacing it by lines 71 to 77 from pop_trimOutlier:
EEGdata2D = single(EEG.data(:,:));
hundredBinUnitLength = floor(EEG.pnts/100);
truncatedData   = EEGdata2D(:,1:hundredBinUnitLength*100);
truncatedData3D = reshape(truncatedData, [size(truncatedData,1) hundredBinUnitLength 100]);
std3D = squeeze(std(truncatedData3D, 0, 2));
stdAllPnts = mean(std3D,2);

But maybe there was a reason for the difference in the calculation? Best, and thanks!

**Comment by MakotoMiyakoshi** [comment]
Hi Mireia,

Thank you for the bug report and using the plugin! I addressed the issue and submitted the updated plugin for the EEGLAB developers. Please wait for several days until it becomes available from a plugin manager. Alternatively, you can directly download the files from this git. SDs are calculated for 100 data bins to use it as a source of variance. I added a tip to readme file/page about how to use this information shown in the error bar. Please let me know if this plugin is more usable now.

**Comment by mireiatorralba** [comment]
Wonderful! It works perfectly. Thanks to you for the plugin is really useful and straightforward to use!
